# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mitgobla\Documents\GitHub\SmartMirror\pimirror\widgets\weather_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_weather_widget(object):
    def setupUi(self, weather_widget):
        weather_widget.setObjectName("weather_widget")
        weather_widget.resize(320, 410)
        weather_widget.setMinimumSize(QtCore.QSize(320, 410))
        weather_widget.setMaximumSize(QtCore.QSize(320, 410))
        weather_widget.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_city = QtWidgets.QLabel(weather_widget)
        self.label_city.setGeometry(QtCore.QRect(0, 0, 320, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_city.setFont(font)
        self.label_city.setAlignment(QtCore.Qt.AlignCenter)
        self.label_city.setObjectName("label_city")
        self.line = QtWidgets.QFrame(weather_widget)
        self.line.setGeometry(QtCore.QRect(10, 30, 301, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_currentweathericon = QtWidgets.QLabel(weather_widget)
        self.label_currentweathericon.setGeometry(QtCore.QRect(30, 60, 91, 91))
        self.label_currentweathericon.setText("")
        self.label_currentweathericon.setPixmap(QtGui.QPixmap("../resources/icons/weather/3200.png"))
        self.label_currentweathericon.setScaledContents(True)
        self.label_currentweathericon.setObjectName("label_currentweathericon")
        self.label_weatherstatus = QtWidgets.QLabel(weather_widget)
        self.label_weatherstatus.setGeometry(QtCore.QRect(20, 170, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_weatherstatus.setFont(font)
        self.label_weatherstatus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_weatherstatus.setWordWrap(True)
        self.label_weatherstatus.setObjectName("label_weatherstatus")
        self.label_currenttemp = QtWidgets.QLabel(weather_widget)
        self.label_currenttemp.setGeometry(QtCore.QRect(140, 60, 91, 91))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_currenttemp.setFont(font)
        self.label_currenttemp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_currenttemp.setObjectName("label_currenttemp")
        self.label_currenthi = QtWidgets.QLabel(weather_widget)
        self.label_currenthi.setGeometry(QtCore.QRect(240, 70, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_currenthi.setFont(font)
        self.label_currenthi.setObjectName("label_currenthi")
        self.label_currentlo = QtWidgets.QLabel(weather_widget)
        self.label_currentlo.setGeometry(QtCore.QRect(240, 110, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_currentlo.setFont(font)
        self.label_currentlo.setObjectName("label_currentlo")
        self.line_2 = QtWidgets.QFrame(weather_widget)
        self.line_2.setGeometry(QtCore.QRect(140, 140, 161, 31))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.label_humidity = QtWidgets.QLabel(weather_widget)
        self.label_humidity.setGeometry(QtCore.QRect(140, 190, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_humidity.setFont(font)
        self.label_humidity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_humidity.setWordWrap(True)
        self.label_humidity.setObjectName("label_humidity")
        self.label_wind = QtWidgets.QLabel(weather_widget)
        self.label_wind.setGeometry(QtCore.QRect(140, 170, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_wind.setFont(font)
        self.label_wind.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_wind.setWordWrap(True)
        self.label_wind.setObjectName("label_wind")
        self.line_3 = QtWidgets.QFrame(weather_widget)
        self.line_3.setGeometry(QtCore.QRect(10, 220, 301, 20))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.label_forecasttitle = QtWidgets.QLabel(weather_widget)
        self.label_forecasttitle.setGeometry(QtCore.QRect(0, 240, 320, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecasttitle.setFont(font)
        self.label_forecasttitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecasttitle.setObjectName("label_forecasttitle")
        self.label_forecastday_1 = QtWidgets.QLabel(weather_widget)
        self.label_forecastday_1.setGeometry(QtCore.QRect(10, 270, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecastday_1.setFont(font)
        self.label_forecastday_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecastday_1.setObjectName("label_forecastday_1")
        self.label_forecastday_2 = QtWidgets.QLabel(weather_widget)
        self.label_forecastday_2.setGeometry(QtCore.QRect(60, 270, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecastday_2.setFont(font)
        self.label_forecastday_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecastday_2.setObjectName("label_forecastday_2")
        self.label_forecastday_3 = QtWidgets.QLabel(weather_widget)
        self.label_forecastday_3.setGeometry(QtCore.QRect(110, 270, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecastday_3.setFont(font)
        self.label_forecastday_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecastday_3.setObjectName("label_forecastday_3")
        self.label_forecastday_4 = QtWidgets.QLabel(weather_widget)
        self.label_forecastday_4.setGeometry(QtCore.QRect(160, 270, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecastday_4.setFont(font)
        self.label_forecastday_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecastday_4.setObjectName("label_forecastday_4")
        self.label_forecastday_5 = QtWidgets.QLabel(weather_widget)
        self.label_forecastday_5.setGeometry(QtCore.QRect(210, 270, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecastday_5.setFont(font)
        self.label_forecastday_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecastday_5.setObjectName("label_forecastday_5")
        self.label_forecastday_6 = QtWidgets.QLabel(weather_widget)
        self.label_forecastday_6.setGeometry(QtCore.QRect(260, 270, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecastday_6.setFont(font)
        self.label_forecastday_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecastday_6.setObjectName("label_forecastday_6")
        self.label_forecasticon_1 = QtWidgets.QLabel(weather_widget)
        self.label_forecasticon_1.setGeometry(QtCore.QRect(20, 290, 31, 31))
        self.label_forecasticon_1.setText("")
        self.label_forecasticon_1.setPixmap(QtGui.QPixmap("../resources/icons/weather/3200.png"))
        self.label_forecasticon_1.setScaledContents(True)
        self.label_forecasticon_1.setObjectName("label_forecasticon_1")
        self.label_forecasticon_2 = QtWidgets.QLabel(weather_widget)
        self.label_forecasticon_2.setGeometry(QtCore.QRect(70, 290, 31, 31))
        self.label_forecasticon_2.setText("")
        self.label_forecasticon_2.setPixmap(QtGui.QPixmap("../resources/icons/weather/3200.png"))
        self.label_forecasticon_2.setScaledContents(True)
        self.label_forecasticon_2.setObjectName("label_forecasticon_2")
        self.label_forecasticon_3 = QtWidgets.QLabel(weather_widget)
        self.label_forecasticon_3.setGeometry(QtCore.QRect(120, 290, 31, 31))
        self.label_forecasticon_3.setText("")
        self.label_forecasticon_3.setPixmap(QtGui.QPixmap("../resources/icons/weather/3200.png"))
        self.label_forecasticon_3.setScaledContents(True)
        self.label_forecasticon_3.setObjectName("label_forecasticon_3")
        self.label_forecasticon_4 = QtWidgets.QLabel(weather_widget)
        self.label_forecasticon_4.setGeometry(QtCore.QRect(170, 290, 31, 31))
        self.label_forecasticon_4.setText("")
        self.label_forecasticon_4.setPixmap(QtGui.QPixmap("../resources/icons/weather/3200.png"))
        self.label_forecasticon_4.setScaledContents(True)
        self.label_forecasticon_4.setObjectName("label_forecasticon_4")
        self.label_forecasticon_5 = QtWidgets.QLabel(weather_widget)
        self.label_forecasticon_5.setGeometry(QtCore.QRect(220, 290, 31, 31))
        self.label_forecasticon_5.setText("")
        self.label_forecasticon_5.setPixmap(QtGui.QPixmap("../resources/icons/weather/3200.png"))
        self.label_forecasticon_5.setScaledContents(True)
        self.label_forecasticon_5.setObjectName("label_forecasticon_5")
        self.label_forecasticon_6 = QtWidgets.QLabel(weather_widget)
        self.label_forecasticon_6.setGeometry(QtCore.QRect(270, 290, 31, 31))
        self.label_forecasticon_6.setText("")
        self.label_forecasticon_6.setPixmap(QtGui.QPixmap("../resources/icons/weather/3200.png"))
        self.label_forecasticon_6.setScaledContents(True)
        self.label_forecasticon_6.setObjectName("label_forecasticon_6")
        self.label_forecasthi_1 = QtWidgets.QLabel(weather_widget)
        self.label_forecasthi_1.setGeometry(QtCore.QRect(10, 330, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecasthi_1.setFont(font)
        self.label_forecasthi_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecasthi_1.setObjectName("label_forecasthi_1")
        self.label_forecastlo_1 = QtWidgets.QLabel(weather_widget)
        self.label_forecastlo_1.setGeometry(QtCore.QRect(10, 350, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecastlo_1.setFont(font)
        self.label_forecastlo_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecastlo_1.setObjectName("label_forecastlo_1")
        self.label_forecasthi_2 = QtWidgets.QLabel(weather_widget)
        self.label_forecasthi_2.setGeometry(QtCore.QRect(60, 330, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecasthi_2.setFont(font)
        self.label_forecasthi_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecasthi_2.setObjectName("label_forecasthi_2")
        self.label_forecasthi_3 = QtWidgets.QLabel(weather_widget)
        self.label_forecasthi_3.setGeometry(QtCore.QRect(110, 330, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecasthi_3.setFont(font)
        self.label_forecasthi_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecasthi_3.setObjectName("label_forecasthi_3")
        self.label_forecasthi_4 = QtWidgets.QLabel(weather_widget)
        self.label_forecasthi_4.setGeometry(QtCore.QRect(160, 330, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecasthi_4.setFont(font)
        self.label_forecasthi_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecasthi_4.setObjectName("label_forecasthi_4")
        self.label_forecasthi_5 = QtWidgets.QLabel(weather_widget)
        self.label_forecasthi_5.setGeometry(QtCore.QRect(210, 330, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecasthi_5.setFont(font)
        self.label_forecasthi_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecasthi_5.setObjectName("label_forecasthi_5")
        self.label_forecasthi_6 = QtWidgets.QLabel(weather_widget)
        self.label_forecasthi_6.setGeometry(QtCore.QRect(260, 330, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecasthi_6.setFont(font)
        self.label_forecasthi_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecasthi_6.setObjectName("label_forecasthi_6")
        self.label_forecastlo_2 = QtWidgets.QLabel(weather_widget)
        self.label_forecastlo_2.setGeometry(QtCore.QRect(60, 350, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecastlo_2.setFont(font)
        self.label_forecastlo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecastlo_2.setObjectName("label_forecastlo_2")
        self.label_forecastlo_3 = QtWidgets.QLabel(weather_widget)
        self.label_forecastlo_3.setGeometry(QtCore.QRect(110, 350, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecastlo_3.setFont(font)
        self.label_forecastlo_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecastlo_3.setObjectName("label_forecastlo_3")
        self.label_forecastlo_4 = QtWidgets.QLabel(weather_widget)
        self.label_forecastlo_4.setGeometry(QtCore.QRect(160, 350, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecastlo_4.setFont(font)
        self.label_forecastlo_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecastlo_4.setObjectName("label_forecastlo_4")
        self.label_forecastlo_5 = QtWidgets.QLabel(weather_widget)
        self.label_forecastlo_5.setGeometry(QtCore.QRect(210, 350, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecastlo_5.setFont(font)
        self.label_forecastlo_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecastlo_5.setObjectName("label_forecastlo_5")
        self.label_forecastlo_6 = QtWidgets.QLabel(weather_widget)
        self.label_forecastlo_6.setGeometry(QtCore.QRect(260, 350, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_forecastlo_6.setFont(font)
        self.label_forecastlo_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecastlo_6.setObjectName("label_forecastlo_6")
        self.label_alerts = QtWidgets.QLabel(weather_widget)
        self.label_alerts.setGeometry(QtCore.QRect(0, 380, 320, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_alerts.setFont(font)
        self.label_alerts.setAlignment(QtCore.Qt.AlignCenter)
        self.label_alerts.setObjectName("label_alerts")

        self.retranslateUi(weather_widget)
        QtCore.QMetaObject.connectSlotsByName(weather_widget)

    def retranslateUi(self, weather_widget):
        _translate = QtCore.QCoreApplication.translate
        self.label_city.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:14pt;\">City Name</span></p></body></html>"))
        self.label_weatherstatus.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Weather Status Weather Status</span></p></body></html>"))
        self.label_currenttemp.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:36pt;\">26°</span></p></body></html>"))
        self.label_currenthi.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:14pt;\">Hi 26°</span></p></body></html>"))
        self.label_currentlo.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:14pt;\">Lo 26°</span></p></body></html>"))
        self.label_humidity.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:10pt;\">Humidity: 100%</span></p></body></html>"))
        self.label_wind.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:10pt;\">Wind: 100 km/h</span></p></body></html>"))
        self.label_forecasttitle.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:11pt;\">Forecast</span></p></body></html>"))
        self.label_forecastday_1.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">Mon</span></p></body></html>"))
        self.label_forecastday_2.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">Tue</span></p></body></html>"))
        self.label_forecastday_3.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">Wed</span></p></body></html>"))
        self.label_forecastday_4.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">Thu</span></p></body></html>"))
        self.label_forecastday_5.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">Fri</span></p></body></html>"))
        self.label_forecastday_6.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">Sat</span></p></body></html>"))
        self.label_forecasthi_1.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">H 26°</span></p></body></html>"))
        self.label_forecastlo_1.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">L 26°</span></p></body></html>"))
        self.label_forecasthi_2.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">H 26°</span></p></body></html>"))
        self.label_forecasthi_3.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">H 26°</span></p></body></html>"))
        self.label_forecasthi_4.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">H 26°</span></p></body></html>"))
        self.label_forecasthi_5.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">H 26°</span></p></body></html>"))
        self.label_forecasthi_6.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">H 26°</span></p></body></html>"))
        self.label_forecastlo_2.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">L 26°</span></p></body></html>"))
        self.label_forecastlo_3.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">L 26°</span></p></body></html>"))
        self.label_forecastlo_4.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">L 26°</span></p></body></html>"))
        self.label_forecastlo_5.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">L 26°</span></p></body></html>"))
        self.label_forecastlo_6.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:9pt;\">L 26°</span></p></body></html>"))
        self.label_alerts.setText(_translate("weather_widget", "<html><head/><body><p><span style=\" font-size:11pt;\">Warnings e.g Flood Alert</span></p></body></html>"))

